(library
 (name core_test)
 (libraries await.blocking await.kernel base_for_tests
   base_test_helpers capsule core core_test_helpers
   expect_test_helpers_core.expect_test_helpers_base expect_test_helpers_core
   expectable core_kernel.fheap unboxed.float32_u
   unboxed.float_u unboxed.int32_u unboxed.int64_u unboxed.nativeint_u
   sexp_grammar_validation sexplib ppx_stable_witness.stable_witness)
 (inline_tests (flags -drop-tag no-js -drop-tag 64-bits-only -drop-tag no-wasm) (modes js wasm) (deps sample_time_zone_file))
 (preprocessor_deps ../src/config.h)
 (preprocess
  (pps ppx_jane ppx_quick_test)))
